// Portfolio data for Rohit Singh

export const personalInfo = {
  name: "Rohit Singh",
  role: "Backend Developer",
  tagline: "Building scalable web applications with modern technologies",
  email: "singhrohit73314@gmail.com",
  phone: "+91 9667305448",
  location: "Delhi, India",
  linkedin: "https://www.linkedin.com/in/rohit-singh-913016229/",
  github: "https://github.com/Rohit73314",
  resumeUrl: "/RohitCv.pdf"
};

export const about = {
  description:
    "Passionate Backend Developer with 1.5+ years of experience specializing in PHP, Laravel, React, and Next.js. I build and optimize scalable web applications with a focus on performance, clean code, and seamless user experiences. My expertise spans API integration, backend optimization, and modern frontend development.",
  highlights: [
    "1.5+ years of professional development experience",
    "Specialized in Laravel, React, Next.js, and MySQL",
    "Built travel & hotel platforms handling 10K+ bookings",
    "Expert in CRM systems, API integration & performance optimization"
  ],
  stats: [
    { label: "Years Of Experience", value: "1.5+" },
    { label: "CRM Features Delivered", value: "20+" },,
    { label: "Performance Gain", value: "30%" },
    { label: "Client Satisfaction", value: "100%" }
  ]
};

export const experience = [
  {
    id: 1,
    company: "Nibble Software Technologies PVT LTD",
    position: "Jr. Backend Developer",
    duration: "April 2025 - Present",
    location: "Delhi, India",
    type: "Full-time",
    responsibilities: [
      "Designed and shipped multi-tenant CRM platforms (Travel, Aviation & Hotel) in Laravel + React/Next.js stack",
      "Integrated REST APIs (Tripjack, HyperGuest, Hotelbeds, Just Click Pay, SendGrid) and optimised backend logic, cutting load times by 40%",
      "Built AI-driven package generator and subscription billing flow for TravoByte (Razorpay + WhatsApp Cloud API)",
      "Collaborated with UI/UX and QA teams to deliver scalable features handling high traffic and concurrent bookings"
    ],
    technologies: ["Laravel", "Next.js", "PHP", "MySQL", "REST APIs", "Razorpay", "WhatsApp API"]
  },
  {
    id: 2,
    company: "Nibble Software Technologies PVT LTD",
    position: "Backend Developer - Trainee",
    duration: "Aug 2024 - Mar 2025",
    location: "Delhi, India",
    type: "Trainee",
    responsibilities: [
      "Assisted in designing and maintaining server-side logic using Laravel for CRM applications",
      "Contributed to feature enhancements, bug fixes, and backend performance optimisation",
      "Improved system stability through rigorous testing and code reviews",
      "Learned best practices in scalable backend architecture"
    ],
    technologies: ["Laravel", "PHP", "MySQL", "Git"]
  }
];

// Helper: Microlink screenshot proxy (no API key needed)
const shot = (url) =>
  `https://api.microlink.io/?url=${encodeURIComponent(
    url
  )}&screenshot=true&meta=false&embed=screenshot.url&viewport.width=1280&viewport.height=800&waitUntil=load`;

export const projects = [
  {
    id: 1,
    title: "TravoByte",
    subtitle: "AI-Powered Subscription Travel CRM (B2C)",
    description:
      "A subscription-based travel management SaaS where every package, itinerary and marketing copy is generated by AI. Supports B2C with multi-vendor capability and WhatsApp client engagement.",
    longDescription:
      "TravoByte is an enterprise-grade travel SaaS that runs on Razorpay subscriptions. Agencies pick a plan, and the platform unlocks AI-generated travel packages, AI quotation builder, multi-vendor booking, WhatsApp Cloud API conversations and a centralised wallet — all from one dashboard.",
    features: [
      "Subscription-based pricing with Razorpay (monthly / yearly plans)",
      "AI-powered travel package generator (itinerary, pricing, copy)",
      "AI-driven quotation builder & smart lead scoring",
      "WhatsApp Cloud API integration for client conversations & alerts",
      "Multi-vendor booking management (Flight + Hotel APIs)",
    ],
    technologies: [
      "Laravel",
      "PHP",
      "MySQL",
      "REST APIs",
      "Razorpay",
      "WhatsApp Cloud API",
      "SendGrid",
      "AI Integration"
    ],
    integrations: [
      "Flight APIs",
      "Hotel APIs",
      "Razorpay Subscriptions",
      "WhatsApp Cloud API",
      "SendGrid",
      "AI / LLM"
    ],
    highlights: [
      { label: "Razorpay Subscriptions", icon: "razorpay" },
      { label: "WhatsApp Cloud API", icon: "whatsapp" },
      { label: "AI-Powered", icon: "ai" }
    ],
    category: "SaaS / CRM",
    image: shot("https://www.travobyte.com/"),
    link: "https://www.travobyte.com/",
    github: "",
    status: "Live",
    impact: "Subscription SaaS with AI-built packages — 10,00+ bookings handled monthly"
  },
  {
    id: 2,
    title: "Metairfare CRM",
    subtitle: "Flight Lead & Customer CRM",
    description:
      "Internal flight CRM for Metairfare that captures every enquiry, routes leads to the right agent and runs daily / weekly conversion & revenue reports for the management team.",
    longDescription:
      "A dedicated CRM for Metairfare's flight desk. The platform centralises lead capture (calls, web, ads), customer profiles, follow-ups and ticketing — and pushes role-based reports that show conversion, source ROI and agent performance.",
    features: [
      "Lead capture from multiple sources with auto assignment",
      "Customer 360 profile with travel history & notes",
      "Agent follow-up tracker with call / SMS / email log",
      "Live conversion & revenue dashboard for management",
      "Daily / weekly / monthly lead reporting with filters",
      "Role-based access for Sales, Supervisor & Admin"
    ],
    technologies: ["Laravel", "PHP", "MySQL", "REST APIs", "Bootstrap"],
    category: "CRM / Aviation",
    image: shot("https://crm.metairfare.com/login"),
    link: "https://crm.metairfare.com/login",
    altLink: "https://www.metairfare.com/",
    github: "",
    status: "Live",
    impact: "Single source of truth for Metairfare's flight sales team"
  },
  {
    id: 3,
    title: "Punjab Aviation",
    subtitle: "Flight Inventory & Booking Platform",
    description:
      "Flight CRM with its own inventory engine, end-to-end booking flow and multi-staff workspace. Agents can hold seats, issue tickets and manage post-sales — all from a single dashboard.",
    longDescription:
      "Punjab Aviation goes beyond a regular CRM. The platform maintains its own flight inventory, supports a full booking flow (search → hold → pay → issue) and allows multiple staff roles to collaborate on every booking with audit trails.",
    features: [
      "Own flight inventory management (routes, fares, seats)",
      "Complete booking flow: search → hold → confirm → ticket",
      "Multi-staff workspace with role-based permissions",
      "Customer & lead management built-in",
      "Payment receipt, refund & cancellation tracking",
      "Inventory & sales reports with date filters"
    ],
    technologies: ["Laravel", "PHP", "MySQL", "REST APIs", "jQuery", "Bootstrap"],
    category: "CRM / Aviation",
    image: shot("https://www.punjabaviation.com/login"),
    link: "https://www.punjabaviation.com/login",
    github: "",
    status: "Live",
    impact: "Powers an aviation business with its own inventory & booking engine"
  },
  {
    id: 4,
    title: "Brhamman",
    subtitle: "Multi-API Hotel Booking Platform",
    description:
      "B2C hotel booking platform aggregating Tripjack, HyperGuest and Hotelbeds plus an own-inventory engine. Agents can add their own properties and manage bookings end-to-end.",
    longDescription:
      "Brhamman pulls hotel inventory from Tripjack, HyperGuest and Hotelbeds and merges it with the agency's own inventory. Agents get a unified search, price comparison, hold & voucher flow, with role-based dashboards for managers and front-desk staff.",
    features: [
      "Tripjack, HyperGuest & Hotelbeds API integration",
      "Own hotel inventory module (rooms, rates, blackout dates)",
      "Unified search across all suppliers with price compare",
      "Agent management with mark-up, commission & wallet",
      "Booking, hold, voucher & cancellation workflow",
      "Role-based dashboards (Admin / Agent / Manager)"
    ],
    technologies: [
      "Laravel",
      "PHP",
      "MySQL",
      "REST APIs",
      "Tripjack API",
      "HyperGuest API",
      "Hotelbeds API"
    ],
    integrations: ["Tripjack", "HyperGuest", "Hotelbeds"],
    highlights: [
      { label: "Tripjack", icon: "plane" },
      { label: "HyperGuest", icon: "hotel" },
      { label: "Hotelbeds", icon: "bed" }
    ],
    category: "Hotel Booking",
    image: shot("https://www.brhamman.com/login"),
    link: "https://www.brhamman.com/login",
    github: "",
    status: "Live",
    impact: "Unified hotel inventory across 3 major suppliers + own inventory"
  },
  // {
  //   id: 5,
  //   title: "Fareease",
  //   subtitle: "B2C Flight & Holiday Booking Site",
  //   description:
  //     "Consumer-facing travel website for Fareease offering flight search, holiday packages and enquiry capture with a clean, conversion-focused funnel.",
  //   longDescription:
  //     "Fareease.in is a consumer travel storefront — flight search, holiday packages, deal banners and enquiry forms — built for high-intent conversions and tightly integrated with the back-office CRM.",
  //   features: [
  //     "Flight search & enquiry flow",
  //     "Holiday & honeymoon package showcase",
  //     "Lead capture forms with CRM hand-off",
  //     "SEO-optimised landing pages",
  //     "Responsive, fast-loading storefront"
  //   ],
  //   technologies: ["Laravel", "PHP", "MySQL", "Bootstrap", "jQuery"],
  //   category: "Travel Website",
  //   image: shot("https://fareease.in/"),
  //   link: "https://fareease.in/",
  //   github: "",
  //   status: "Live"
  // },
  {
    id: 5,
    title: "FFD Travels",
    subtitle: "Travel Agency Storefront & Enquiry Engine",
    description:
      "Marketing & booking enquiry site for FFD Travels — packages, destinations and lead capture pushed straight into the agency's CRM.",
    longDescription:
      "FFDTravels.com is the agency's public face. Visitors browse destinations & packages, request quotes and chat with the team — all enquiries route into the agency's CRM for follow-up.",
    features: [
      "Curated destination & package pages",
      "Quote request & lead capture forms",
      "Newsletter & marketing opt-in",
      "Mobile-first responsive design",
      "CRM hand-off for every enquiry"
    ],
    technologies: ["Laravel", "PHP", "MySQL", "Bootstrap"],
    category: "Travel Website",
    image: shot("https://www.ffdtravels.com/"),
    link: "https://www.ffdtravels.com/",
    github: "",
    status: "Live"
  },
  // {
  //   id: 7,
  //   title: "World Travels Network",
  //   subtitle: "B2B Travel Network Portal",
  //   description:
  //     "B2B portal for travel partners — onboarding, agent wallets, bookings and reporting in a single login for the World Travels Network ecosystem.",
  //   longDescription:
  //     "World Travels Network is a B2B portal where partner agents log in, top-up wallets, access negotiated fares and manage their bookings & reports under a single network identity.",
  //   features: [
  //     "Partner / agent onboarding flow",
  //     "Wallet top-up & ledger management",
  //     "Booking & cancellation workflows",
  //     "Sales & wallet reports per agent",
  //     "Multi-role access (Admin / Agent / Accounts)"
  //   ],
  //   technologies: ["Laravel", "PHP", "MySQL", "REST APIs", "Bootstrap"],
  //   category: "B2B Portal",
  //   image: shot("https://www.worldtravelsnetwork.com/"),
  //   link: "https://www.worldtravelsnetwork.com/",
  //   github: "",
  //   status: "Live"
  // },
  {
    id: 6,
    title: "Birthdaymasti",
    subtitle: "E-commerce Cake Ordering Platform",
    description:
      "An in-house developed cake e-commerce platform offering a delightful selection of cakes for every occasion. Features intuitive UI, secure payments and efficient order management.",
    longDescription:
      "Built from scratch, Birthdaymasti provides customers with a seamless online cake ordering experience. The platform handles inventory management, order tracking and payment processing with robust security measures.",
    features: [
      "Product catalog with advanced filtering",
      "Shopping cart and wishlist functionality",
      "Secure payment gateway integration",
      "Real-time order tracking system",
      "Admin panel for inventory management",
      "Customer reviews and ratings",
      "Promotional offers and discount management"
    ],
    technologies: ["Laravel", "Next.js", "PHP", "JavaScript", "MySQL", "REST APIs"],
    category: "E-commerce",
    image: shot("https://birthdaymasti.com"),
    link: "https://birthdaymasti.com",
    github: "",
    status: "Live"
  },
  {
    id: 7,
    title: "Karzandolls",
    subtitle: "E-commerce — Diecast models, action figures, collectibles",
    description:
      // "Rebuilt an existing collectibles e-commerce site on a modern stack — Laravel backend + Next.js storefront, with DTDC shipping fully managed from the admin panel.",
      "Online store with catalog browsing, wishlist, and secure checkout. Developed and maintained as part of the e-commerce portfolio.",
    longDescription:
      "A complete platform overhaul focusing on performance, user experience and scalability. Implemented modern best practices and optimised for high traffic scenarios, including backend-managed shipping operations via DTDC integration.",
    features: [
      "Product catalog with advanced filtering and search",
      "Wishlist and cart management",
      "Secure authentication and payment integration",
      "Order tracking and history",
      "Scalable Laravel admin panel",
      "Fast, responsive Next.js storefront",
      "Inventory and promotion management",
      "Backend-managed DTDC shipping (creation, tracking, status updates)",
      "Preorder Flow"
    ],
    technologies: [
      "Laravel",
      // "Next.js",
      "MySQL",
      "REST APIs",
      "Payment Integration",
      "DTDC Shipping API"
    ],
    category: "E-commerce",
    image: shot("https://www.karzanddolls.com/"),
    link: "https://www.karzanddolls.com/",
    github: "",
    status: "Completed"
  },
  {
    id: 8,
    title: "Alumni Tracking System",
    subtitle: "Alumni Management Platform",
    description:
      "A comprehensive system to manage alumni data and improve engagement. Features include profile management, event coordination and networking capabilities.",
    features: [
      "Alumni profile management",
      "Event coordination and RSVP system",
      "Networking and messaging features",
      "Job board for alumni opportunities",
      "Analytics dashboard for engagement metrics"
    ],
    technologies: ["PHP", "Laravel", "MySQL", "Bootstrap"],
    category: "Web Application",
    image: "",
    link: "https://rohit73314.github.io/alumni-tracking-system/",
    github: "",
    status: "Completed"
  }
];

export const skills = {
  backend: [
    { name: "Laravel", level: 90 },
    { name: "PHP", level: 88 },
    { name: "Node.js", level: 75 },
    { name: "Express.js", level: 72 },
    { name: "RESTful APIs", level: 85 },
    { name: "Authentication", level: 80 }
  ],
  frontend: [
    { name: "React.js", level: 85 },
    { name: "Next.js", level: 82 },
    { name: "JavaScript", level: 88 },
    { name: "Tailwind CSS", level: 80 },
    { name: "Bootstrap", level: 80 }
  ],
  database: [
    { name: "MySQL", level: 90 },
    { name: "MongoDB", level: 75 },
    { name: "Firebase", level: 70 }
  ],
  tools: [
    { name: "Git", level: 85 },
    { name: "GitHub", level: 85 },
    { name: "AWS EC2", level: 70 },
    { name: "Razorpay", level: 78 }
  ],
  other: [
    { name: "DSA", level: 75 },
    { name: "DBMS", level: 82 },
    { name: "OS", level: 78 },
    { name: "Problem Solving", level: 85 }
  ]
};

export const education = [
  {
    id: 1,
    degree: "Master of Computer Applications (MCA)",
    institution: "Ganga Institute of Technology and Management",
    duration: "Sep 2022 - July 2024",
    grade: "7.20 CGPA",
    location: "Delhi, India"
  },
  {
    id: 2,
    degree: "Bachelor of Computer Applications (BCA)",
    institution: "Ganga Institute of Technology and Management",
    duration: "Aug 2019 - July 2022",
    grade: "7.53 CGPA",
    location: "Delhi, India"
  }
];

export const achievements = [
  {
    id: 1,
    title: "National-Level Hackathon Participant",
    description:
      "Represented team and received positive feedback for innovative project presentation",
    year: "2023"
  },
  {
    id: 2,
    title: "Multi-Tenant CRM Architect",
    description:
      "Designed CRM platforms used by aviation, hotel and travel businesses with multi-staff workflows",
    year: "2024"
  },
  {
    id: 3,
    title: "Performance Optimization Expert",
    description: "Reduced application load times by 40% through backend & query optimisation",
    year: "2024"
  },
  {
    id: 4,
    title: "AI + Payments Integration",
    description:
      "Shipped Razorpay subscriptions, WhatsApp Cloud API and AI package generation in TravoByte",
    year: "2025"
  }
];

export const testimonials = [
  {
    id: 1,
    name: "Tech Lead",
    position: "Senior Developer, Nibble Software",
    content:
      "Rohit is an exceptional developer with strong problem-solving skills. His ability to quickly adapt to new technologies and deliver high-quality code is impressive."
  },
  {
    id: 2,
    name: "Project Manager",
    position: "Manager, Nibble Software",
    content:
      "Working with Rohit has been a pleasure. He consistently delivers projects on time and his attention to detail in both frontend and backend development is commendable."
  }
];
